apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: developeriq
    app.kubernetes.io/instance: developeriq-instance
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: kubectl
  name: developeriq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: developeriq
  template:
    metadata:
      labels:
        app: developeriq
    spec:
      containers:
        - image: 412485745957.dkr.ecr.us-east-1.amazonaws.com/developeriq:latest
          imagePullPolicy: Always
          name: developeriq
          ports:
            - containerPort: 5000
