apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: developeriq
    app.kubernetes.io/instance: developeriq-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: developeriq
spec:
  selector:
    app: developeriq
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 5000
